from ..formatter import format_col_name


reisource = [
    'OWNER 1 LABEL NAME',
    'OWNER 1 LAST NAME',
    'OWNER 1 FIRST NAME',
    'OWNER 1 MIDDLE NAME',
    'OWNER 1 SUFFIX',
    'OWNER 2 LABEL NAME',
    'OWNER 2 LAST NAME',
    'OWNER 2 FIRST NAME',
    'OWNER 2 MIDDLE NAME',
    'OWNER 2 SUFFIX',
    'OWNER CARE OF NAME',
    'MAIL ADDRESS',
    'MAIL CITY',
    'MAIL STATE',
    'MAIL ZIP CODE',
    'MAIL ZIP+4',
    'MAIL ZIP/ZIP+4',
    'MAIL CARRIER ROUTE',
    'MAIL COUNTRY',
    'PROPERTY ADDRESS',
    'PROPERTY HOUSE NUMBER',
    'PROPERTY HOUSE NUMBER PREFIX',
    'PROPERTY HOUSE NUMBER SUFFIX',
    'PROPERTY HOUSE NUMBER 2',
    'PROPERTY PRE DIRECTION',
    'PROPERTY STREET NAME',
    'PROPERTY STREET NAME SUFFIX',
    'PROPERTY POST DIRECTION',
    'PROPERTY UNIT NUMBER',
    'PROPERTY CITY',
    'PROPERTY STATE',
    'PROPERTY ZIP CODE',
    'PROPERTY ZIP+4',
    'PROPERTY ZIP/ZIP+4',
    'PROPERTY CARRIER ROUTE',
    'COUNTY',
    'PROPERTY TYPE',
    'LAST MARKET SALE DATE',
    'ASSESSMENT YEAR',
    'BATHROOMS',
    'BEDROOMS',
    'BLDG/LIVING AREA',
    'CENSUS TRACT',
    'COUNTY LAND USE CODE',
    'FIRST MORTGAGE AMOUNT',
    'FIRST MORTGAGE DATE',
    'FIRST MORTGAGE INTEREST RATE',
    'FIRST MORTGAGE LENDER NAME',
    'FIRST MORTGAGE LOAN RATE TYPE',
    'FIRST MORTGAGE MATURITY DATE',
    'FIRST MORTGAGE PRIMARY LOAN TYPE',
    'HOMESTEAD EXEMPTION',
    'IMPROVED %',
    'IMPROVED VALUE',
    'JUNIOR 1 MTG AMOUNT',
    'JUNIOR 1 MTG DATE',
    'JUNIOR 1 MTG INTEREST RATE',
    'JUNIOR 1 MTG LENDER NAME',
    'JUNIOR 1 MTG LOAN RATE TYPE',
    'JUNIOR 1 MTG MATURITY DATE',
    'JUNIOR 1 MTG PRIMARY LOAN TYPE',
    'JUNIOR 2 MTG AMOUNT',
    'JUNIOR 2 MTG INTEREST RATE',
    'JUNIOR 2 MTG LENDER NAME',
    'JUNIOR 2 MTG LOAN RATE TYPE',
    'JUNIOR 2 MTG MATURITY DATE',
    'JUNIOR 2 MTG MORTGAGE DATE',
    'JUNIOR 2 MTG PRIMARY LOAN TYPE',
    'LAND VALUE',
    'LAST MARKET RECORDING DATE',
    'LAST MARKET SALE DEED TYPE',
    'LAST MARKET SALE PRICE TYPE',
    'LAST MARKET SALE PRICE',
    'LOT AREA',
    'LOT ACREAGE',
    'OWNER OCCUPIED',
    'OWNER TRANSFER RECORDING DATE',
    'OWNER TRANSFER SALE DATE',
    'OWNER TRANSFER SALE PRICE',
    'PARCEL ID',
    'ALTERNATE APN',
    'PRIOR MARKET RECORDING DATE',
    'PRIOR MARKET SALE DATE',
    'PRIOR MARKET SALE PRICE',
    'PROPERTY TAX AMOUNT',
    'STATE LAND USE CODE',
    'SWIMMING POOL PRESENT',
    'TOTAL ASSESSED VALUE',
    'YEAR BUILT',
    'JUNIOR 1 MTG BALLOON LOAN',
    'JUNIOR 1 MTG CREDIT LINE LOAN',
    'JUNIOR 1 MTG EQUITY LOAN',
    'JUNIOR 1 MTG LENDER ADDRESS',
    'JUNIOR 1 MTG LENDER CITY',
    'JUNIOR 1 MTG LENDER STATE',
    'JUNIOR 1 MTG LENDER ZIP CODE',
    'JUNIOR 1 MTG LENDER ZIP+4',
    'JUNIOR 1 MTG MATURED',
    'JUNIOR 1 MTG PRIVATE PARTY LOAN',
    'JUNIOR 1 MTG SELLER CARRY BACK',
    'JUNIOR 1 MTG TERM',
    'JUNIOR 1 MTG TRANSACTION TYPE',
    'JUNIOR 2 MTG BALLOON LOAN',
    'JUNIOR 2 MTG CREDIT LINE LOAN',
    'JUNIOR 2 MTG EQUITY LOAN',
    'JUNIOR 2 MTG MATURED',
    'JUNIOR 2 MTG PRIVATE PARTY LOAN',
    'JUNIOR 2 MTG SELLER CARRY BACK',
    'JUNIOR 2 MTG TERM',
    'JUNIOR 2 MTG TRANSACTION TYPE',
    'X'
]


def test_format():
    colname = 'OWNER 1 LABEL NAME'
    correct = 'owner_1_label_name'

    new_colname = format_col_name(colname)

    assert new_colname == correct


def test_all():
    clean_cols = []
    for c in reisource:
        new_col = format_col_name(c)
        clean_cols.append(new_col)
    print clean_cols

    assert clean_cols == []


if __name__ == '__main__':
	test_format()
