corelogic = {
    'FIPS CODE': 'string',
    'APN UNFORMATTED': 'string',
    'APN FORMATTED': 'string',
    'APN SEQUENCE NUMBER': 'string',
    'ORIGINAL APN': 'string',
    'THOMAS BROS MAP NUMBER': 'string',
    'MAP REFERENCE 1': 'string',
    'MAP REFERENCE 2': 'string',
    'CENSUS TRACT': 'string',
    'BLOCK NUMBER': 'string',
    'LOT NUMBER': 'string',
    'RANGE': 'string',
    'TOWNSHIP': 'string',
    'SECTION': 'string',
    'QUARTER SECTION': 'string',
    'FLOOD ZONE COMMUNITY PANEL ID': 'string',
    'UNIVERSAL LAND USE CODE': 'string',
    'COUNTY LAND USE 2': 'string',
    'COUNTY LAND USE 1': 'string',
    'ZONING': 'string',
    'PROPERTY INDICATOR CODE': 'string',
    'MOBILE HOME INDICATOR FLAG': 'string',
    'LATITUDE': 'string',
    'LONGITUDE': 'string',
    'PROPERTY HOUSE NUMBER PREFIX': 'string',
    'PROPERTY HOUSE NUMBER': 'string',
    'PROPERTY HOUSE NUMBER #2': 'string',
    'PROPERTY HOUSE NUMBER SUFFIX': 'string',
    'PROPERTY DIRECTION': 'string',
    'PROPERTY STREET NAME': 'string',
    'PROPERTY MODE': 'string',
    'PROPERTY QUADRANT': 'string',
    'PROPERTY APARTMENT UNIT NUMBER': 'string',
    'PROPERTY CITY': 'string',
    'PROPERTY STATE': 'string',
    'PROPERTY ZIPCODE': 'string',
    'ABSENTEE INDICATOR CODE': 'string',
    'OWNER CORPORATE INDICATOR FLAG': 'string',
    'OWNER 1 LAST NAME': 'string',
    'OWNER 1 FIRST NAME & MI': 'string',
    'OWNER 2 LAST NAME': 'string',
    'OWNER 2 FIRST NAME & MI': 'string',
    'OWNER RELATIONSHIP TYPE CODE': 'string',
    'OWNER OWNERSHIP RIGHTS CODE': 'string',
    'OWNER ETAL INDICATOR CODE': 'string',
    'MAIL HOUSE NUMBER PREFIX': 'string',
    'MAIL HOUSE NUMBER': 'string',
    'MAIL HOUSE NUMBER #2': 'string',
    'MAIL DIRECTION': 'string',
    'MAIL HOUSE NUMBER SUFFIX': 'string',
    'MAIL STREET NAME': 'string',
    'MAIL MODE': 'string',
    'MAIL QUADRANT': 'string',
    'MAIL APARTMENT UNIT NUMBER': 'string',
    'MAIL CITY': 'string',
    'MAIL STATE': 'string',
    'MAIL ZIPCODE': 'string',
    'ASSD TOTAL VALUE': 'string',
    'ASSD LAND VALUE': 'string',
    'ASSD IMPROVEMENT VALUE': 'string',
    'APPR TOTAL VALUE': 'string',
    'APPR LAND VALUE': 'string',
    'APPR IMPROVEMENT VALUE': 'string',
    'MKT TOTAL VALUE': 'string',
    'MKT LAND VALUE': 'string',
    'MKT IMPROVEMENT VALUE': 'string',
    'TAX AMOUNT': 'string',
    'TAX YEAR': 'string',
    'ASSESSED YEAR': 'string',
    'BATCH ID': 'string',
    'BATCH SEQ': 'string',
    'MULTI APN FLAG CODE': 'string',
    'MULTI APN COUNT': 'string',
    'SALES DOCUMENT TYPE CODE': 'string',
    'RECORDING DATE': 'string',
    'SALE AMOUNT': 'string',
    'SALE DATE': 'string',
    'SALE CODE': 'string',
    'INTER FAMILY': 'string',
    'SALES TRANSACTION TYPE CODE': 'string',
    'SELLER NAME 1': 'string',
    'SELLER NAME 2': 'string',
    'SELLER LAST NAME': 'string',
    'SELLER FIRST NAME': 'string',
    '1ST MORTGAGE AMOUNT': 'string',
    '1ST MORTGAGE LOAN TYPE CODE': 'string',
    '1ST MORTGAGE DEED TYPE CODE': 'string',
    '1ST MORTGAGE DATE': 'string',
    'PRIOR SALE TRANSACTION TYPE CODE': 'string',
    'PRIOR SALE AMOUNT': 'string',
    'PRIOR SALE DATE': 'string',
    'PRIOR SALE CODE': 'string',
    'PRIOR SALE RECORDING DATE': 'string',
    'PRIOR SALE MORTGAGE AMOUNT': 'string',
    'PRIOR SALE DOCUMENT TYPE CODE': 'string',
    'PRIOR BATCH SEQ': 'string',
    'PRIOR BATCH ID': 'string',
    'ACRES': 'string',
    'LAND SQUARE FOOTAGE': 'string',
    'UNIVERSAL BUILDING SQUARE FEET': 'string',
    'UNIVERSAL BUILDING SQUARE FEET INDICATOR CODE': 'string',
    'BUILDING SQUARE FEET': 'string',
    'GARAGE PARKING SQUARE FEET': 'string',
    'GARAGE CODE': 'string',
    'YEAR BUILT': 'string',
    'EFFECTIVE YEAR BUILT': 'string',
    'VIEW': 'string',
    'POOL CODE': 'string',
    'POOL FLAG': 'string',
    'PARKING TYPE CODE': 'string',
    'PARKING SPACES': 'string',
    'ROOF TYPE CODE': 'string',
    'ROOF COVER CODE': 'string',
    'QUALITY CODE': 'string',
    'TOTAL BATHS': 'string',
    'FRAME CODE': 'string',
    'FOUNDATION CODE': 'string',
    'FLOOR CODE': 'string',
    'FIREPLACE TYPE CODE': 'string',
    'FIREPLACE NUMBER': 'string',
    'FIREPLACE INDICATOR FLAG': 'string',
    'FINISHED BASEMENT AREA': 'string',
    'EXTERIOR WALLS CODE': 'string',
    'CONSTRUCTION TYPE CODE': 'string',
    'CONDITION CODE': 'string',
    'BLDG IMPROVEMENT CODE': 'string',
    'BLDG CODE': 'string',
    'BASEMENT FINISH CODE': 'string',
    'STORIES NUMBER': 'string',
    'STORIES CODE': 'string',
    'HEATING CODE': 'string',
    'UNFINISHED BASEMENT AREA': 'string',
    'UNITS NUMBER': 'string',
    'SELLER CARRYBACK': 'string',
    'PRIVATE PARTY LENDER': 'string',
    'PRI CAT CODE': 'string',
    'MTG SEC CAT CODES': 'string',
    'DEED SEC CAT CODES': 'string',
    'CLTV': 'string',
    'LEGAL 1': 'string',
    'LEGAL 2': 'string',
    'LEGAL 3': 'string',
    'ADD CHANGE FLAG': 'string',
    'REFID': 'string',
    'INPUT FIPS CODE': 'string',
    'INPUT PARCEL ID': 'string',
    'PROPERTY MATCH CODE': 'string',
    'EXCEPTION CODE'
}