schema_reisource = {
    'OWNER 1 LABEL NAME': 'string',
    'OWNER 1 LAST NAME': 'string',
    'OWNER 1 FIRST NAME': 'string',
    'OWNER 1 MIDDLE NAME': 'string',
    'OWNER 1 SUFFIX': 'string',
    'OWNER 2 LABEL NAME': 'string',
    'OWNER 2 LAST NAME': 'string',
    'OWNER 2 FIRST NAME': 'string',
    'OWNER 2 MIDDLE NAME': 'string',
    'OWNER 2 SUFFIX': 'string',
    'OWNER CARE OF NAME': 'string',
    'MAIL ADDRESS': 'string',
    'MAIL CITY': 'string',
    'MAIL STATE': 'string',
    'MAIL ZIP CODE': 'string',
    'MAIL ZIP+4': 'string',
    'MAIL ZIP/ZIP+4': 'string',
    'MAIL CARRIER ROUTE': 'string',
    'MAIL COUNTRY': 'string',
    'PROPERTY ADDRESS': 'string',
    'PROPERTY HOUSE NUMBER': 'string',
    'PROPERTY HOUSE NUMBER PREFIX': 'string',
    'PROPERTY HOUSE NUMBER SUFFIX': 'string',
    'PROPERTY HOUSE NUMBER 2': 'string',
    'PROPERTY PRE DIRECTION': 'string',
    'PROPERTY STREET NAME': 'string',
    'PROPERTY STREET NAME SUFFIX': 'string',
    'PROPERTY POST DIRECTION': 'string',
    'PROPERTY UNIT NUMBER': 'string',
    'PROPERTY CITY': 'string',
    'PROPERTY STATE': 'string',
    'PROPERTY ZIP CODE': 'string',
    'PROPERTY ZIP+4': 'string',
    'PROPERTY ZIP/ZIP+4': 'string',
    'PROPERTY CARRIER ROUTE': 'string',
    'COUNTY': 'string',
    'PROPERTY TYPE': 'string',
    'LAST MARKET SALE DATE': 'string',
    'ASSESSMENT YEAR': 'string',
    'BATHROOMS': 'string',
    'BEDROOMS': 'string',
    'BLDG/LIVING AREA': 'string',
    'CENSUS TRACT': 'string',
    'COUNTY LAND USE CODE': 'string',
    'FIRST MORTGAGE AMOUNT': 'string',
    'FIRST MORTGAGE DATE': 'string',
    'FIRST MORTGAGE INTEREST RATE': 'string',
    'FIRST MORTGAGE LENDER NAME': 'string',
    'FIRST MORTGAGE LOAN RATE TYPE': 'string',
    'FIRST MORTGAGE MATURITY DATE': 'string',
    'FIRST MORTGAGE PRIMARY LOAN TYPE': 'string',
    'HOMESTEAD EXEMPTION': 'string',
    'IMPROVED %': 'string',
    'IMPROVED VALUE': 'string',
    'JUNIOR 1 MTG AMOUNT': 'string',
    'JUNIOR 1 MTG DATE': 'string',
    'JUNIOR 1 MTG INTEREST RATE': 'string',
    'JUNIOR 1 MTG LENDER NAME': 'string',
    'JUNIOR 1 MTG LOAN RATE TYPE': 'string',
    'JUNIOR 1 MTG MATURITY DATE': 'string',
    'JUNIOR 1 MTG PRIMARY LOAN TYPE': 'string',
    'JUNIOR 2 MTG AMOUNT': 'string',
    'JUNIOR 2 MTG INTEREST RATE': 'string',
    'JUNIOR 2 MTG LENDER NAME': 'string',
    'JUNIOR 2 MTG LOAN RATE TYPE': 'string',
    'JUNIOR 2 MTG MATURITY DATE': 'string',
    'JUNIOR 2 MTG MORTGAGE DATE': 'string',
    'JUNIOR 2 MTG PRIMARY LOAN TYPE': 'string',
    'LAND VALUE': 'string',
    'LAST MARKET RECORDING DATE': 'string',
    'LAST MARKET SALE DEED TYPE': 'string',
    'LAST MARKET SALE PRICE TYPE': 'string',
    'LAST MARKET SALE PRICE': 'int',
    'LOT AREA': 'string',
    'LOT ACREAGE': 'string',
    'OWNER OCCUPIED': 'string',
    'OWNER TRANSFER RECORDING DATE': 'string',
    'OWNER TRANSFER SALE DATE': 'string',
    'OWNER TRANSFER SALE PRICE': 'int',
    'PARCEL ID': 'string',
    'ALTERNATE APN': 'string',
    'PRIOR MARKET RECORDING DATE': 'string',
    'PRIOR MARKET SALE DATE': 'string',
    'PRIOR MARKET SALE PRICE': 'int',
    'PROPERTY TAX AMOUNT': 'string',
    'STATE LAND USE CODE': 'string',
    'SWIMMING POOL PRESENT': 'string',
    'TOTAL ASSESSED VALUE': 'string',
    'YEAR BUILT': 'int',
    'JUNIOR 1 MTG BALLOON LOAN': 'string',
    'JUNIOR 1 MTG CREDIT LINE LOAN': 'string',
    'JUNIOR 1 MTG EQUITY LOAN': 'string',
    'JUNIOR 1 MTG LENDER ADDRESS': 'string',
    'JUNIOR 1 MTG LENDER CITY': 'string',
    'JUNIOR 1 MTG LENDER STATE': 'string',
    'JUNIOR 1 MTG LENDER ZIP CODE': 'string',
    'JUNIOR 1 MTG LENDER ZIP+4': 'string',
    'JUNIOR 1 MTG MATURED': 'string',
    'JUNIOR 1 MTG PRIVATE PARTY LOAN': 'string',
    'JUNIOR 1 MTG SELLER CARRY BACK': 'string',
    'JUNIOR 1 MTG TERM': 'string',
    'JUNIOR 1 MTG TRANSACTION TYPE': 'string',
    'JUNIOR 2 MTG BALLOON LOAN': 'string',
    'JUNIOR 2 MTG CREDIT LINE LOAN': 'string',
    'JUNIOR 2 MTG EQUITY LOAN': 'string',
    'JUNIOR 2 MTG MATURED': 'string',
    'JUNIOR 2 MTG PRIVATE PARTY LOAN': 'string',
    'JUNIOR 2 MTG SELLER CARRY BACK': 'string',
    'JUNIOR 2 MTG TERM': 'string',
    'JUNIOR 2 MTG TRANSACTION TYPE': 'string',
    'X': 'string'
}